Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PFD_SaveTheEnvironment.DAL;
using PFD_SaveTheEnvironment.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.Extensions.Logging;

namespace PFD_SaveTheEnvironment.Controllers
{
    public class HomeController : Controller
    {
        private UsersDAL userContext = new UsersDAL();

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoginPage()
        {
            if (HttpContext.Session.GetString("Role") == "User")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public ActionResult Login(IFormCollection FormData)
        {
            if (HttpContext.Session.GetString("Role") == "User")
            {
                return RedirectToAction("Index", "Home");
            }

            string email = FormData["txtLoginID"].ToString();
            string password = FormData["txtPassword"].ToString();
            DateTime DateTiming = DateTime.Now;

            if (userContext.ValidUserLogin(email, password) == true)
            {
                string Role = "User";
                HttpContext.Session.SetString("Role", Role);
                string userID = Convert.ToString(userContext.GetUserID(email));
                HttpContext.Session.SetString("LoginID", userID);
                ViewData["UserID"] = userID.ToString();
                HttpContext.Session.SetString("LogInTime", DateTiming.ToString());

                return RedirectToAction("Index");
            }
            else
            {
                TempData["Message"] = "Invalid Login Credentials";
                return RedirectToAction("LoginPage");
            }
        }
        public ActionResult userLogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
    }
}

Controllers/ReadController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PFD_SaveTheEnvironment.Controllers
{
    public class ReadController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Organizations()
        {
            return View();
        }

        public IActionResult Cars()
        {
            return View();
        }

        public IActionResult Energy()
        {
            return View();
        }

        public IActionResult Electronics()
        {
            return View();
        }

        public IActionResult Fashion()
        {
            return View();
        }

        public IActionResult FoodandBeverages()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width,
                                           initial-scale = 1" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" type="image/x-icon" href="~/images/favicon.ico" />
</head>
<body>
    <br />
    <h1 class="font-weight-bold text-center">🌎 PolyEarth 🌎</h1>
    <h5 class="text-center">There's only One Earth, Don't Throw it Away</h5>
    <hr />
    <p class="text-center">An educational website, packed with tons of interactive features to keep users engaged and educate them about the environmental issues caused by large companies around the world.</p>
    <hr />
    <br />
    <div class="iframe-container">
        <iframe width="280" height="157" src="https://www.youtube.com/embed/wbR-5mHI6bo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <small class="text-muted">(Video from Kurzgesagt; https://www.youtube.com/watch?v=wbR-5mHI6bo&t=1s) </small>
    <br />
    <br />
    <hr />
    <br />
    <h3 class="text-center">Learning Materials We Offer</h3>
    <br />
    <p class="text-center">As you have probably heard from various media outlets before, the Earth has been on a bad track for many years now, with daily carbon emissions increasing as developing countries continue to grow. This has led to Global Warming becoming an extremely prevalent issue. On this site, we have provided some reading materials, looking at how companies contribute to this issue and why we should protect the Earth!</p>
    <br />
    <div class="row">
        <div class="course-col">
            <a asp-action="Cars" asp-controller="Read" style="text-decoration:none">
                <h3 class="text-dark">Cars</h3>
                <p class="text-muted">Read more about car companies that are good or bad for the environment and how they impact the environment</p>
            </a>
        </div>
        <div class="course-col">
            <a asp-action="Fashion" asp-controller="Read" style="text-decoration:none">
                <h3 class="text-dark">Fashion</h3>
                <p class="text-muted">Read more about fashion companies that are good or bad for the environment and how they impact the environment</p>
            </a>
        </div>
        <div class="course-col">
            <a asp-action="Energy" asp-controller="Read" style="text-decoration:none">
                <h3 class="text-dark">Energy</h3>
                <p class="text-muted">Read more about sources of energy that are good or bad for the environment and how they impact the environment</p>
            </a>
        </div>
        <div class="course-col">
            <a asp-action="FoodandBeverages" asp-controller="Read" style="text-decoration:none">
                <h3 class="text-dark">F&B</h3>
                <p class="text-muted">Read more about food and beverages companies that are good or bad for the environment and how they impact the environment</p>
            </a>
        </div>
        <div class="course-col">
            <a asp-action="Electronics" asp-controller="Read" style="text-decoration:none">
                <h3 class="text-dark">Electronics</h3>
                <p class="text-muted">Read more about electronic companies that are good or bad for the environment and how they impact the environment</p>
            </a>
        </div>
    </div>
    <hr />
    <section class="footer">
        <h3>About the creators</h3>
        <br />
        This informative website was developed by, Kwek Yufeng Jordan, Kai Lucas Anton, Keane Dominic Travasso, Muhammad Dandarawie Bin Rohani and Loong Chor Yi, to help bring awareness to the declining state of the environment/climate and how certain beloved companies actually contribute to this issue. The website also focuses on user interaction for engagement, as seen by the many games and inputs.
        <br /><br />
        <hr />
        <div class="p-3">
            <h3 class="text-center">Contact Us</h3>
            <form target="_blank" action="https://formsubmit.co/pfdkaigrp@gmail.com" method="POST">
                <br />
                <div class="form-group">
                    <div class="form-row">
                        <div class="col">
                            <input type="text" name="Name" class="form-control" placeholder="Full Name" required>
                        </div>
                        <div class="col">
                            <input type="email" name="Email" class="form-control" placeholder="Email Address" required>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <textarea placeholder="Your Message" class="form-control" name="Message" rows="3" required></textarea>
                </div>
                <button type="submit" class="btn btn-lg btn-dark btn-block">Submit Form</button>
                <br />
            </form>
        </div>
    </section>
    <section>
        <br />
        <hr />
        <div class="reddit-feed" style="text-align: center;">
            <h1>Reddit Feed</h1>
            <p>Tips on how you can save the environment</p>
            <div id="reddit-post"></div>
        </div>
        <br />
    </section>
    <script src="~/js/reddit.js"></script>
</body>

</html>

Views/Home/LoginPage.cshtml
@{ ViewData["Title"] = "Log In Page";}

<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width,
                                           initial-scale = 1" />
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
</head>
<body>
    <div class="heading">
        <br />
        <h1 class="text-center font-weight-bold">PolyEarth</h1>
        <h3 class="text-center">Log In</h3>
        <hr />
    </div>
    @if (TempData["Success"] != null)
    {
<h5 class="text-success text-center">@TempData["Success"]</h5>
                <br />}
    <div class="container">
        <div class="row gutters-sm">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center">
                            <form method="post" action="~/Home/Login">
                                <fieldset class="loginFieldset">
                                    <br />
                                    <div class="container-fluid">
                                        <div class="row justify-content-center">
                                            <div class="form-group">
                                                <h6>Email:</h6>
                                                <input class="form-control rounded-pill border-3 border-primary" placeholder="Email" type="email" name="txtLoginID" id="txtLoginID" required />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="container-fluid">
                                        <div class="row justify-content-center">
                                            <div class="form-group col-md-12">
                                                <h6>Password:</h6>
                                                <input class="form-control rounded-pill border-3 border-primary" placeholder="Password" type="password" name="txtPassword" id="txtPassword" required />
                                            </div>
                                        </div>
                                    </div>
                                    <br />
                                    <div class="container-fluid">
                                        <div class="row justify-content-center">
                                            <div class="form-group">
                                                <input type="submit" id="btnLogin" value="Login" class="btn btn-primary rounded-pill" />
                                            </div>
                                        </div>
                                    </div>
                                    <br />
                                    <div class="container-fluid">
                                        <div class="row justify-content-center">
                                            <span style="color:red  ;">@TempData["Message"]</span>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="text-center">
            <br />
            <span class="font-weight-bold">Don't Have an Account?</span>
            <br />
            <a href="~/User/Create">Create an Account</a>
        </div>
    </div>
</body>
</html>